#In Python, the Dictionary data types represent the implementation of hash tables. The Keys in the dictionary satisfy the following requirements:

#The keys of the dictionary are hashable i.e. the are generated by hashing function which generates unique result for each unique value supplied to the hash function.

#The order of data elements in a dictionary is not fixed.

dic = {'llave1':'valor1', 'llave2':'valor1'}

dic['llave3'] = 'valor3'

print(dic)